### ISSUE TITLE
#lhs_toc autoscrolling

### ISSUE THREAD

**Issue by binset** [binset/wikitoc#12]
Can I suggest adding the option to... autoscrolling so that the table of contents scrolls as you go to a different section?

https://www.reddit.com/r/firefox/comments/33cex8/firefox_addon_that_enhances_the_toctable_of/cqkcz6m

**Comment by teamrc** [comment]
This can be done easy by adding the following tags to the #lhs_toc section 
tabindex="1" id="blahblah" 

Once tabindex has been defined, you can focus on the li using:
$("#yea").trigger("focus");

**Comment by teamrc** [comment]
Issue has been fixed.
